---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-exporter
  labels:
    app.kubernetes.io/name: nvidia-exporter
    app.kubernetes.io/part-of: nvidia-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nvidia-exporter
        app.kubernetes.io/part-of: nvidia-exporter
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      runtimeClassName: nvidia
      containers:
      - name: nvidia-exporter
        image: ghcr.io/cosandr/nvidia-exporter:v1.1.0
        ports:
          - name: http
            containerPort: 9401
        livenessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 30
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
          runAsNonRoot: false
          runAsUser: 0
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nvidia-exporter
  labels:
    app.kubernetes.io/part-of: nvidia-exporter
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - nvidia-exporter
  podMetricsEndpoints:
    - port: http
